version: '3.7'
services:
  frontend:
    build: .
    image: parking-lot-manager-frontend:0.0.1
    container_name: parking-lot-manager-frontend
    environment:
      JAVA_TOOL_OPTIONS: -Xms1G -Xmx1G -Djava.security.egd=file:/dev/./urandom
      TZ: Asia/Seoul
    restart: always
    ports:
      - 3000:3000
    networks:
      - frontend
    depends_on:
      - api-server

  api-server:
    build: .
    image: parking-lot-manager:0.0.1
    container_name: parking-lot-manager
    environment:
      SPRING_PROFILES_ACTIVE: stag
      SEOUL_OPEN_API_BASE_URL: http://openapi.seoul.go.kr:8088
      SEOUL_OPEN_API_AUTH_KEY: your-auth-key
      DATABASE_URL: jdbc:mysql://mysql-server:3306/parking-lot-manager?useSSL=false&characterEncoding=utf8
      DATABASE_USERNAME: parkinglotuser
      DATABASE_PASSWORD: parkinglotuser
      ROOT_LOG_LEVEL: DEBUG
      JAVA_TOOL_OPTIONS: -Xms1G -Xmx1G -Djava.security.egd=file:/dev/./urandom
      TZ: Asia/Seoul
    restart: always
    ports:
      - 8080:8080
    networks:
      - frontend
      - backend
    depends_on:
      - mysql-server

  mysql-server:
    image: mysql:5.7
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --skip-character-set-client-handshake
    environment:
      MYSQL_DATABASE: parking-lot-manager
      MYSQL_USER: parkinglotuser
      MYSQL_PASSWORD: parkinglotuser
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:

networks:
  frontend:
  backend:
