DROP TABLE IF EXISTS `PARKING_LOT_INFORMATION`;

CREATE TABLE `PARKING_LOT_INFORMATION`
(
    `CODE`                        VARCHAR(100) NOT NULL,
    `NAME`                        VARCHAR(100) NOT NULL,
    `ADDRESS`                     VARCHAR(100) NOT NULL,
    `TYPE`                        VARCHAR(5)   NOT NULL,
    `BUSINESS_TYPE`               VARCHAR(5)   NOT NULL,
    `TEL`                         VARCHAR(30),
    `TOTAL_PARKING_SLOT_COUNT`    INT                   DEFAULT 0,
    `PARKING_CARS_COUNT`          INT                   DEFAULT 0,
    `PAID_SERVICE`                VARCHAR(2)   NOT NULL,
    `NIGHT_FREE_OPEN`             VARCHAR(2)   NOT NULL,
    `WEEKDAY_OPENING_TIME`        VARCHAR(5)   NOT NULL,
    `WEEKDAY_CLOSING_TIME`        VARCHAR(5)   NOT NULL,
    `WEEKEND_OPENING_TIME`        VARCHAR(5)   NOT NULL,
    `WEEKEND_CLOSING_TIME`        VARCHAR(5)   NOT NULL,
    `HOLIDAY_OPENING_TIME`        VARCHAR(5)   NOT NULL,
    `HOLIDAY_CLOSING_TIME`        VARCHAR(5)   NOT NULL,
    `UPDATED_TIME`                TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `SATURDAY_PAY_YN`             VARCHAR(2)   NOT NULL,
    `HOLIDAY_PAY_YN`              VARCHAR(2)   NOT NULL,
    `MONTHLY_COMMUTER_PASS_PRICE` VARCHAR(10)   NOT NULL,
    `BASIC_PARKING_FEE`           DOUBLE,
    `BASIC_PARKING_MIN`           DOUBLE,
    `ADDITIONAL_PARKING_FEE`      DOUBLE,
    `ADDITIONAL_PARKING_MIN`      DOUBLE,
    `BUS_BASIC_PARKING_FEE`       DOUBLE,
    `BUS_BASIC_PARKING_MIN`       DOUBLE,
    `BUS_ADDITIONAL_PARKING_FEE`  DOUBLE,
    `BUS_ADDITIONAL_PARKING_MIN`  DOUBLE,
    `DAILY_LIMIT_CHARGE_AMOUNT`   DOUBLE,
    `LATITUDE`                    DOUBLE,
    `LONGITUDE`                   DOUBLE,
    PRIMARY KEY (`CODE`)
) DEFAULT CHARSET=utf8;

CREATE INDEX `IDX_PARKING_LOT_INFORMATION_NAME` ON `PARKING_LOT_INFORMATION` (`NAME`);
CREATE INDEX `IDX_PARKING_LOT_INFORMATION_ADDRESS` ON `PARKING_LOT_INFORMATION` (`ADDRESS`);
CREATE INDEX `IDX_PARKING_LOT_INFORMATION_TEL` ON `PARKING_LOT_INFORMATION` (`TEL`);
CREATE INDEX `IDX_PARKING_LOT_INFORMATION_BASIC_PARKING_FEE` ON `PARKING_LOT_INFORMATION` (`BASIC_PARKING_FEE`);
